---
name: Claude Fix File Path Export
on:
  workflow_dispatch:

env:
  ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

jobs:
  claude-fix-file-paths:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Prompt Claude to Fix File Export
        run: |
          cd ~ && nix-shell -p nodejs expect --run 'expect -c "
            set timeout 600
            log_file -noappend claude-fix-output.log
            spawn npx @anthropic-ai/claude-code --dangerously-skip-permissions \"Clone https://github.com/garmir/claude-methodology.git to ~/.claude then analyze the workflow artifact upload issues. Fix the file path export problem where claude-output.txt is not being created properly. Create working files and test the fix.\"
            expect { -re {.*Choose.*style.*} { send \"1\r\" } }
            expect { -re {.*bypass permissions.*} { send \"2\r\" } }
            expect {
              -re {.*fix.*|.*file.*|.*path.*|.*export.*|.*Write.*} {
                sleep 45
              }
              eof {
                exit 0
              }
              timeout {
                exit 1
              }
            }
          "'
      - name: Copy All Output Files
        run: |
          nix-shell -p coreutils --run 'cp ~/claude-fix-output.log . 2>/dev/null || echo "No log" > error.txt'
          nix-shell -p coreutils --run 'ls -la ~ > home-listing.txt'
          nix-shell -p coreutils --run 'find ~ -name "*.txt" -o -name "*.md" -o -name "*.log" > file-search.txt'
      - name: Upload All Results
        uses: actions/upload-artifact@v4
        with:
          name: claude-fix-results
          path: |
            claude-fix-output.log
            error.txt
            home-listing.txt
            file-search.txt